//! SSH host model and summary types.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::DeviceType;
use crate::vpn::profile::SecretRef;

/// How the SSH session authenticates to the remote host.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AuthMethod {
    /// Password-based authentication.
    Password,
    /// Public-key authentication.
    Key,
}

/// A saved port-forwarding rule (local → remote via SSH tunnel).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PortForward {
    /// Local TCP port to listen on.
    pub local_port: u16,
    /// Remote host to forward to (as seen from the SSH server).
    pub remote_host: String,
    /// Remote TCP port to forward to.
    pub remote_port: u16,
    /// Optional human-readable description.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

/// Default SSH port (22).
fn default_port() -> u16 {
    22
}

/// A managed SSH host.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SshHost {
    /// Unique identifier (generated by the daemon on creation).
    #[serde(default = "uuid::Uuid::new_v4")]
    pub id: Uuid,

    /// Human-readable label for this host.
    pub label: String,

    /// Hostname or IP address.
    pub hostname: String,

    /// SSH port number.
    #[serde(default = "default_port")]
    pub port: u16,

    /// Login username.
    pub username: String,

    /// Logical group for organising hosts (e.g. "web", "db").
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub group: String,

    /// Type of device behind this host.
    #[serde(default)]
    pub device_type: DeviceType,

    /// Authentication method.
    pub auth_method: AuthMethod,

    /// ID of the SSH key used when `auth_method` is [`AuthMethod::Key`].
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub auth_key_id: Option<Uuid>,

    /// Reference to the password stored in the secret service.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub auth_password_ref: Option<SecretRef>,

    /// Optional VPN profile to auto-connect before opening this SSH session.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub vpn_profile_id: Option<Uuid>,

    /// FortiGate REST API port (typically 443).  Only used when
    /// `device_type` is [`DeviceType::Fortigate`].
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub api_port: Option<u16>,

    /// Reference to the FortiGate REST API token in the secret service.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub api_token_ref: Option<SecretRef>,

    /// Skip TLS certificate verification for FortiGate REST API calls.
    #[serde(default)]
    pub api_verify_tls: bool,

    /// UniFi Controller URL (e.g. "https://unifi.example.com:8443").
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub unifi_controller_url: Option<String>,

    /// Reference to the UniFi Controller API credentials in the secret service.
    /// Stored as JSON: `{"username": "...", "password": "..."}`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub unifi_api_token_ref: Option<SecretRef>,

    /// Saved port-forwarding rules for this host.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub port_forwards: Vec<PortForward>,

    /// UUID of another SSH host to use as a jump/bastion host (ProxyJump).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub proxy_jump: Option<Uuid>,

    /// Whether this host is pinned/favourited (appears at the top of lists).
    #[serde(default)]
    pub pinned: bool,

    /// When this host was created.
    #[serde(default = "chrono::Utc::now")]
    pub created_at: DateTime<Utc>,

    /// When this host was last modified.
    #[serde(default = "chrono::Utc::now")]
    pub updated_at: DateTime<Utc>,
}

/// Lightweight summary of an [`SshHost`] for list views.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SshHostSummary {
    /// Unique identifier.
    pub id: Uuid,

    /// Human-readable label.
    pub label: String,

    /// Hostname or IP address.
    pub hostname: String,

    /// SSH port number.
    pub port: u16,

    /// Login username.
    pub username: String,

    /// Logical group.
    pub group: String,

    /// Type of device.
    pub device_type: DeviceType,

    /// Authentication method.
    pub auth_method: AuthMethod,

    /// ID of the SSH key used when `auth_method` is [`AuthMethod::Key`].
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub auth_key_id: Option<Uuid>,

    /// Optional VPN profile to auto-connect before opening this SSH session.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub vpn_profile_id: Option<Uuid>,

    /// Whether a FortiGate REST API token is configured for this host.
    #[serde(default)]
    pub has_api: bool,

    /// FortiGate REST API port (for display in edit dialog).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub api_port: Option<u16>,

    /// Whether a UniFi Controller URL is configured for this host.
    #[serde(default)]
    pub has_unifi_controller: bool,

    /// Saved port-forwarding rules.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub port_forwards: Vec<PortForward>,

    /// UUID of another SSH host to use as a jump/bastion host (ProxyJump).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub proxy_jump: Option<Uuid>,

    /// Whether this host is pinned/favourited.
    #[serde(default)]
    pub pinned: bool,
}

impl From<&SshHost> for SshHostSummary {
    fn from(host: &SshHost) -> Self {
        Self {
            id: host.id,
            label: host.label.clone(),
            hostname: host.hostname.clone(),
            port: host.port,
            username: host.username.clone(),
            group: host.group.clone(),
            device_type: host.device_type,
            auth_method: host.auth_method,
            auth_key_id: host.auth_key_id,
            vpn_profile_id: host.vpn_profile_id,
            has_api: host.api_token_ref.is_some(),
            api_port: host.api_port,
            has_unifi_controller: host.unifi_controller_url.is_some(),
            port_forwards: host.port_forwards.clone(),
            proxy_jump: host.proxy_jump,
            pinned: host.pinned,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Helper to build a minimal `SshHost` for testing.
    fn sample_host() -> SshHost {
        SshHost {
            id: Uuid::nil(),
            label: "test-server".into(),
            hostname: "192.168.1.10".into(),
            port: 22,
            username: "admin".into(),
            group: "web".into(),
            device_type: DeviceType::Linux,
            auth_method: AuthMethod::Key,
            auth_key_id: Some(Uuid::nil()),
            auth_password_ref: None,
            vpn_profile_id: None,
            api_port: Some(443),
            api_token_ref: Some(SecretRef::new("tok")),
            api_verify_tls: true,
            unifi_controller_url: Some("https://unifi.local:8443".into()),
            unifi_api_token_ref: None,
            port_forwards: vec![],
            proxy_jump: None,
            pinned: true,
            created_at: Utc::now(),
            updated_at: Utc::now(),
        }
    }

    #[test]
    fn host_summary_from_host() {
        let host = sample_host();
        let summary = SshHostSummary::from(&host);

        assert_eq!(summary.id, host.id);
        assert_eq!(summary.label, "test-server");
        assert_eq!(summary.hostname, "192.168.1.10");
        assert_eq!(summary.port, 22);
        assert_eq!(summary.username, "admin");
        assert_eq!(summary.group, "web");
        assert_eq!(summary.device_type, DeviceType::Linux);
        assert_eq!(summary.auth_method, AuthMethod::Key);
        assert_eq!(summary.auth_key_id, Some(Uuid::nil()));
        assert!(summary.has_api, "api_token_ref is Some so has_api should be true");
        assert_eq!(summary.api_port, Some(443));
        assert!(summary.has_unifi_controller);
        assert!(summary.pinned);
    }

    #[test]
    fn default_port_is_22() {
        assert_eq!(default_port(), 22);

        // Also verify via serde: a JSON host without a `port` field gets 22.
        let json = r#"{
            "label": "no-port",
            "hostname": "example.com",
            "username": "root",
            "auth_method": "password"
        }"#;
        let host: SshHost = serde_json::from_str(json).expect("deserialize host without port");
        assert_eq!(host.port, 22);
    }

    #[test]
    fn auth_method_serde() {
        // AuthMethod uses snake_case rename.
        let json = serde_json::to_string(&AuthMethod::Password).unwrap();
        assert_eq!(json, r#""password""#);

        let json = serde_json::to_string(&AuthMethod::Key).unwrap();
        assert_eq!(json, r#""key""#);

        // Round-trip
        let rt: AuthMethod = serde_json::from_str(r#""key""#).unwrap();
        assert_eq!(rt, AuthMethod::Key);
    }

    #[test]
    fn device_type_serde_snake_case() {
        // DeviceType uses snake_case rename.
        let json = serde_json::to_string(&DeviceType::Linux).unwrap();
        assert_eq!(json, r#""linux""#);

        let json = serde_json::to_string(&DeviceType::PfSense).unwrap();
        assert_eq!(json, r#""pf_sense""#);

        let json = serde_json::to_string(&DeviceType::Fortigate).unwrap();
        assert_eq!(json, r#""fortigate""#);

        let rt: DeviceType = serde_json::from_str(r#""open_wrt""#).unwrap();
        assert_eq!(rt, DeviceType::OpenWrt);
    }
}
