//! SSH host model and summary types.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::DeviceType;
use crate::vpn::profile::SecretRef;

/// How the SSH session authenticates to the remote host.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AuthMethod {
    /// Password-based authentication.
    Password,
    /// Public-key authentication.
    Key,
}

/// Default SSH port (22).
fn default_port() -> u16 {
    22
}

/// A managed SSH host.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SshHost {
    /// Unique identifier (generated by the daemon on creation).
    #[serde(default = "uuid::Uuid::new_v4")]
    pub id: Uuid,

    /// Human-readable label for this host.
    pub label: String,

    /// Hostname or IP address.
    pub hostname: String,

    /// SSH port number.
    #[serde(default = "default_port")]
    pub port: u16,

    /// Login username.
    pub username: String,

    /// Logical group for organising hosts (e.g. "web", "db").
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub group: String,

    /// Type of device behind this host.
    #[serde(default)]
    pub device_type: DeviceType,

    /// Authentication method.
    pub auth_method: AuthMethod,

    /// ID of the SSH key used when `auth_method` is [`AuthMethod::Key`].
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub auth_key_id: Option<Uuid>,

    /// Reference to the password stored in the secret service.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub auth_password_ref: Option<SecretRef>,

    /// Optional VPN profile to auto-connect before opening this SSH session.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub vpn_profile_id: Option<Uuid>,

    /// FortiGate REST API port (typically 443).  Only used when
    /// `device_type` is [`DeviceType::Fortigate`].
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub api_port: Option<u16>,

    /// Reference to the FortiGate REST API token in the secret service.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub api_token_ref: Option<SecretRef>,

    /// Skip TLS certificate verification for FortiGate REST API calls.
    #[serde(default)]
    pub api_verify_tls: bool,

    /// UniFi Controller URL (e.g. "https://unifi.example.com:8443").
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub unifi_controller_url: Option<String>,

    /// Reference to the UniFi Controller API credentials in the secret service.
    /// Stored as JSON: `{"username": "...", "password": "..."}`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub unifi_api_token_ref: Option<SecretRef>,

    /// Whether this host is pinned/favourited (appears at the top of lists).
    #[serde(default)]
    pub pinned: bool,

    /// When this host was created.
    #[serde(default = "chrono::Utc::now")]
    pub created_at: DateTime<Utc>,

    /// When this host was last modified.
    #[serde(default = "chrono::Utc::now")]
    pub updated_at: DateTime<Utc>,
}

/// Lightweight summary of an [`SshHost`] for list views.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SshHostSummary {
    /// Unique identifier.
    pub id: Uuid,

    /// Human-readable label.
    pub label: String,

    /// Hostname or IP address.
    pub hostname: String,

    /// SSH port number.
    pub port: u16,

    /// Login username.
    pub username: String,

    /// Logical group.
    pub group: String,

    /// Type of device.
    pub device_type: DeviceType,

    /// Authentication method.
    pub auth_method: AuthMethod,

    /// ID of the SSH key used when `auth_method` is [`AuthMethod::Key`].
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub auth_key_id: Option<Uuid>,

    /// Optional VPN profile to auto-connect before opening this SSH session.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub vpn_profile_id: Option<Uuid>,

    /// Whether a FortiGate REST API token is configured for this host.
    #[serde(default)]
    pub has_api: bool,

    /// FortiGate REST API port (for display in edit dialog).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub api_port: Option<u16>,

    /// Whether a UniFi Controller URL is configured for this host.
    #[serde(default)]
    pub has_unifi_controller: bool,

    /// Whether this host is pinned/favourited.
    #[serde(default)]
    pub pinned: bool,
}

impl From<&SshHost> for SshHostSummary {
    fn from(host: &SshHost) -> Self {
        Self {
            id: host.id,
            label: host.label.clone(),
            hostname: host.hostname.clone(),
            port: host.port,
            username: host.username.clone(),
            group: host.group.clone(),
            device_type: host.device_type,
            auth_method: host.auth_method,
            auth_key_id: host.auth_key_id,
            vpn_profile_id: host.vpn_profile_id,
            has_api: host.api_token_ref.is_some(),
            api_port: host.api_port,
            has_unifi_controller: host.unifi_controller_url.is_some(),
            pinned: host.pinned,
        }
    }
}
