import AppKit
import SwiftUI

/// Menu-bar dropdown content. Compact glanceable view of every
/// long-running connection — Tailscale state, active VPN profiles,
/// daemon health — without forcing the user to bring the main
/// window forward. Click an item to bring the relevant section up.
///
/// The dropdown's CONTENT lives here. The state-driven status-bar
/// ICON is generated by `SuperManagerApp` via the `MenuBarExtra`'s
/// `systemImage` parameter, which it derives from `appState`.
struct MenuBarView: View {
    @Environment(AppState.self) private var appState
    @Environment(\.openWindow) private var openWindow

    var body: some View {
        // Daemon health
        if appState.daemonAvailable {
            Label("Daemon: connected", systemImage: "checkmark.circle.fill")
                .foregroundStyle(.green)
        } else {
            Label("Daemon: offline", systemImage: "exclamationmark.circle.fill")
                .foregroundStyle(.red)
        }

        Divider()

        // ----- Tailscale -----
        if let s = appState.tailscaleStatus {
            switch s.backendState {
            case "Running":
                let activeExitNode = appState.tailscalePrefs?.currentExitNode(in: s.peers)
                if let exit = activeExitNode {
                    Label("Tailscale: exit via \(exit.hostName)",
                          systemImage: "arrow.up.forward.circle.fill")
                } else {
                    Label("Tailscale: connected (\(s.peers.count) peers)",
                          systemImage: "globe.americas.fill")
                }
                Button("Disconnect Tailscale") {
                    Task { await appState.tailscaleDown() }
                }
            case "Stopped":
                Label("Tailscale: disconnected",
                      systemImage: "globe.americas")
                Button("Connect Tailscale") {
                    Task { await appState.tailscaleUp() }
                }
            case "NeedsLogin":
                Label("Tailscale: sign-in required",
                      systemImage: "person.crop.circle.badge.questionmark")
            default:
                Label("Tailscale: \(s.backendState)",
                      systemImage: "globe.americas")
            }
        } else if appState.tailscaleIsBundled {
            Label("Tailscale daemon not running",
                  systemImage: "globe.americas")
        }

        Divider()

        // ----- VPN profiles (only show connected/connecting) -----
        let connectedProfiles = appState.vpnProfiles.filter { p in
            let s = appState.vpnConnectionStates[p.id] ?? "disconnected"
            return s == "connected" || s == "connecting"
        }
        if connectedProfiles.isEmpty {
            Label("VPN: no active tunnels", systemImage: "lock.shield")
        } else {
            ForEach(connectedProfiles, id: \.id) { p in
                vpnRow(for: p)
            }
        }

        Divider()

        // ----- Window + actions -----
        Button("Open SuperManager") {
            // Bringing the main window to front when the user
            // clicks here is what they expect; the alternative
            // (keep app running headless) is annoying when the
            // user just wants to inspect state.
            for window in NSApp.windows {
                if window.title == "SuperManager" || window.contentViewController != nil {
                    window.makeKeyAndOrderFront(nil)
                    NSApp.activate(ignoringOtherApps: true)
                    return
                }
            }
            NSApp.activate(ignoringOtherApps: true)
        }
        .keyboardShortcut("o")

        Divider()

        Button("Disconnect All VPNs") {
            Task { await appState.disconnectAllVpns() }
        }
        .disabled(connectedProfiles.isEmpty)

        Divider()

        Button("Quit SuperManager") {
            NSApplication.shared.terminate(nil)
        }
        .keyboardShortcut("q")
    }

    /// One row in the connected-VPN list. Extracted from the
    /// inline MenuBar body because the type-checker timed out on
    /// the combined string interpolation + foregroundStyle ternary
    /// (see Swift forums on "compiler is unable to type-check").
    @ViewBuilder
    private func vpnRow(for p: VpnProfileSummary) -> some View {
        let s = appState.vpnConnectionStates[p.id] ?? "disconnected"
        let ao = appState.autoReconnectEnabled.contains(p.id)
        let icon = s == "connected" ? "lock.shield.fill" : "lock.shield"
        let stateText = s == "connected" ? "connected" : "connecting…"
        let aoSuffix = ao ? " · always-on" : ""
        let title = "\(p.name): \(stateText)\(aoSuffix)"
        Label(title, systemImage: icon)
        Button("Disconnect \(p.name)") {
            Task { await appState.forceDisconnect(profileId: p.id) }
        }
    }
}
