#!/usr/bin/env bash
# Enable passwordless sudo for the specific binaries SuperManager's
# dev workflow needs.
#
# What this does
# --------------
# Writes `/etc/sudoers.d/supermanager-dev` with NOPASSWD entries for
# the user, scoped to:
#   • /usr/bin/install   — installs helper binary into /Library/PrivilegedHelperTools
#   • /bin/cp            — fallback for install operations
#   • /bin/chmod         — set helper binary permissions
#   • /usr/sbin/chown    — set helper binary ownership
#   • /bin/rm            — cleanup of installed files
#   • /bin/launchctl     — bootstrap/bootout of LaunchDaemon
#   • /bin/mkdir         — ensure target directory exists
#
# These cover everything `install_helper.sh` and the helper-uninstall
# flow need. NOT a blanket NOPASSWD — `sudo bash` and friends still
# prompt for password.
#
# **This is dev-machine-only**. Don't run on a shared / production
# Mac. Remove with `disable_nopasswd.sh` (or `sudo rm /etc/sudoers.d/supermanager-dev`)
# when you're done with the dev session.
#
# Validation
# ----------
# `visudo -c -f` is run on the rendered file to catch syntax errors
# before they brick sudo. If validation fails, the file is removed
# and the script exits non-zero.

set -euo pipefail

USER_NAME="$(whoami)"
SUDOERS_FILE="/etc/sudoers.d/supermanager-dev"

# Render to a temp file first so we can validate before installing.
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

cat > "$TMP" <<EOF
# SuperManager dev workflow — passwordless sudo for installer +
# LaunchDaemon operations only. Scoped to a fixed list of system
# binaries; everything else still prompts for a password.
#
# Generated by SuperManager/Signing/enable_nopasswd.sh on $(date -u +%FT%TZ)
# Disable with: sudo rm $SUDOERS_FILE
${USER_NAME} ALL=(ALL) NOPASSWD: /usr/bin/install, /bin/cp, /bin/chmod, /usr/sbin/chown, /bin/rm, /bin/launchctl, /bin/mkdir
EOF

# Sudoers files MUST be 0440 root:wheel — anything else and sudo
# refuses to load them.
echo "→ Writing $SUDOERS_FILE (will prompt for sudo this one time)…"
sudo install -m 0440 -o root -g wheel "$TMP" "$SUDOERS_FILE"

# Validate. visudo -c -f exits non-zero on syntax error.
if ! sudo visudo -c -f "$SUDOERS_FILE" >/dev/null; then
    echo "error: sudoers file failed validation — removing." >&2
    sudo rm -f "$SUDOERS_FILE"
    exit 1
fi

echo "✓ NOPASSWD enabled for the SuperManager dev workflow."
echo ""
echo "  Allowed binaries (no password prompt):"
echo "    install, cp, chmod, chown, rm, launchctl, mkdir"
echo ""
echo "  Disable when done:"
echo "    sudo rm $SUDOERS_FILE"
echo "  or run:"
echo "    $(dirname "$0")/disable_nopasswd.sh"
