# Stage Cygwin's openfortivpn binary + DLL closure into
# `vendor/openfortivpn-bundle/`, then emit a WiX include fragment
# (`installer/wix/openfortivpn-files.wxi`) that registers each file
# under the MSI's `bin\openfortivpn-bundle\` directory.
#
# Why this dance:
#   * openfortivpn upstream has no Windows port. Cygwin packages it,
#     producing a Cygwin-runtime-linked .exe. The .exe needs
#     cygwin1.dll + a half-dozen support DLLs co-located in its own
#     directory (Cygwin's mmap-fork semantics break if cygwin1.dll
#     ends up loaded twice from different paths).
#   * pppd is required at runtime by openfortivpn for the actual PPP
#     negotiation. Cygwin's ppp package provides it.
#   * We bundle the closure into a dedicated subdirectory so it
#     doesn't pollute the main bin directory and doesn't conflict
#     with any system Cygwin install the user might have.
#
# Inputs:
#   - $CygwinRoot   default C:\cygwin (matches cygwin/cygwin-install-action defaults)
#   - $RepoRoot     repo root (auto-detected)
#
# Outputs:
#   - vendor/openfortivpn-bundle/openfortivpn.exe
#   - vendor/openfortivpn-bundle/pppd.exe
#   - vendor/openfortivpn-bundle/*.dll (every cyg*.dll the two .exes pull in)
#   - installer/wix/openfortivpn-files.wxi  (auto-generated, .gitignore'd)

[CmdletBinding()]
param(
    [string]$CygwinRoot = $env:CYGWIN_ROOT,
    [string]$RepoRoot   = (Split-Path -Parent (Split-Path -Parent $PSScriptRoot))
)

$ErrorActionPreference = "Stop"

if (-not $CygwinRoot) {
    # cygwin/cygwin-install-action defaults to C:\cygwin; fall back to
    # the common alternative path used by the standalone setup-x86_64.exe
    foreach ($candidate in @("C:\cygwin", "C:\cygwin64", "D:\cygwin")) {
        if (Test-Path "$candidate\bin\cygcheck.exe") {
            $CygwinRoot = $candidate
            break
        }
    }
}
if (-not $CygwinRoot -or -not (Test-Path "$CygwinRoot\bin\cygcheck.exe")) {
    throw "Cygwin not found. Install via cygwin/cygwin-install-action or set CYGWIN_ROOT."
}

$cygBin       = Join-Path $CygwinRoot "bin"
$cygSbin      = Join-Path $CygwinRoot "sbin"
$openfortivpn = Join-Path $cygBin  "openfortivpn.exe"
$pppd         = Join-Path $cygSbin "pppd.exe"
if (-not (Test-Path $pppd)) { $pppd = Join-Path $cygBin "pppd.exe" }

foreach ($p in @($openfortivpn, $pppd)) {
    if (-not (Test-Path $p)) {
        throw "Missing $p - make sure Cygwin install included the openfortivpn + ppp packages."
    }
}

$bundleDir = Join-Path $RepoRoot "vendor/openfortivpn-bundle"
if (Test-Path $bundleDir) {
    Remove-Item $bundleDir -Recurse -Force
}
New-Item -ItemType Directory -Path $bundleDir | Out-Null

# Resolve the DLL closure via cygcheck. Output looks like:
#   C:\cygwin\bin\openfortivpn.exe
#     C:\cygwin\bin\cygwin1.dll
#       C:\WINDOWS\system32\KERNEL32.dll
#       ...
# We pick only the lines that resolve under $CygwinRoot - those are
# the DLLs we need to ship; the WINDOWS\system32 ones are present on
# every target by definition.
function Get-CygwinDllClosure {
    param([string]$ExePath)
    & "$cygBin\cygcheck.exe" $ExePath 2>$null |
        ForEach-Object { $_.Trim() } |
        Where-Object {
            $_ -match '\\\\?[Cc]ygwin\\\\bin\\\\' -or
            $_ -match [regex]::Escape($CygwinRoot)
        } |
        ForEach-Object { $_ -replace '^\s*', '' } |
        Where-Object { $_ -match '\.dll$' } |
        Sort-Object -Unique
}

$dlls = New-Object System.Collections.Generic.HashSet[string]
foreach ($exe in @($openfortivpn, $pppd)) {
    foreach ($d in Get-CygwinDllClosure -ExePath $exe) {
        [void]$dlls.Add($d)
    }
}

Write-Host "openfortivpn DLL closure: $($dlls.Count) entries"

# Stage everything into the bundle dir.
Copy-Item $openfortivpn (Join-Path $bundleDir "openfortivpn.exe")
Copy-Item $pppd         (Join-Path $bundleDir "pppd.exe")
foreach ($d in $dlls) {
    $leaf = Split-Path -Leaf $d
    Copy-Item $d (Join-Path $bundleDir $leaf)
}

# Strip MOTW (Zone Identifier) so WiX doesn't trip on alternate-data-streams.
Get-ChildItem -Path $bundleDir | Unblock-File

# Emit the WiX fragment. Each file becomes its own <Component> +
# <File>; the parent directory `BinOpenfortivpnDir` is declared
# in supermanager.wxs.
$wxi = @()
$wxi += "<?xml version=`"1.0`" encoding=`"UTF-8`"?>"
$wxi += "<!-- AUTO-GENERATED by scripts/windows/Stage-Openfortivpn.ps1. Do not edit by hand. -->"
$wxi += "<Include xmlns=`"http://wixtoolset.org/schemas/v4/wxs`">"
$componentIds = New-Object System.Collections.ArrayList
foreach ($f in (Get-ChildItem $bundleDir | Sort-Object Name)) {
    # WiX component / file ids must be C-identifier-like.
    $safeId = ($f.Name -replace '[^A-Za-z0-9_]', '_')
    $compId = "OfvBundle_$safeId"
    [void]$componentIds.Add($compId)
    $wxi += "  <Component Id=`"$compId`" Directory=`"BinOpenfortivpnDir`" Bitness=`"always64`">"
    $wxi += "    <File Id=`"OfvFile_$safeId`" Source=`"vendor\openfortivpn-bundle\$($f.Name)`" KeyPath=`"yes`" />"
    $wxi += "  </Component>"
}
$wxi += ""
$wxi += "  <ComponentGroup Id=`"OpenfortivpnBundleGroup`">"
foreach ($cid in $componentIds) {
    $wxi += "    <ComponentRef Id=`"$cid`" />"
}
$wxi += "  </ComponentGroup>"
$wxi += "</Include>"

$wxiPath = Join-Path $RepoRoot "installer/wix/openfortivpn-files.wxi"
$wxi -join "`r`n" | Out-File -FilePath $wxiPath -Encoding utf8
Write-Host "Wrote $wxiPath ($($componentIds.Count) components)"
