//! VPN kill-switch via macOS' packet filter (`pf`).
//!
//! When a user toggles `kill_switch=true` on a VPN profile, this
//! module installs a pf anchor that:
//!
//!   1. Allows local LAN traffic (RFC1918 + link-local)
//!   2. Allows traffic via the tunnel interface (utun*)
//!   3. Blocks everything else
//!
//! On disconnect, the anchor is flushed and pf returns to whatever
//! state it was in before. Idempotent — repeated installs replace
//! the existing rule set.
//!
//! ## Why pf and not `route` blackhole + DNS
//!
//! - `route add -net 0.0.0.0/0 -blackhole` only catches IPv4 and
//!   doesn't enforce that traffic must go through utun (it just
//!   stops it from going anywhere). Apps see "no route" and may
//!   bind to a specific interface as a workaround.
//! - pf's `block all out except via utun*` is the canonical leak
//!   prevention. Same approach Tailscale.app, Mullvad, etc use.
//!
//! ## Anchor name
//!
//! `com.sybr.supermanager.killswitch` — under
//! `/etc/pf.anchors/`, loaded into the main `pf.conf` ruleset
//! via `pfctl -a com.sybr.supermanager.killswitch`. Doesn't
//! interfere with any existing pf rules the user might have.

use anyhow::{bail, Context, Result};
use serde::{Deserialize, Serialize};
use std::fs;
use std::path::Path;
use std::process::Command;

const ANCHOR_NAME: &str = "com.sybr.supermanager.killswitch";
const ANCHOR_FILE: &str = "/etc/pf.anchors/com.sybr.supermanager.killswitch";

#[derive(Deserialize, Debug)]
pub struct EnableArgs {
    /// The tunnel interface to allow egress through, e.g.
    /// `utun7`. Caller must already know which utun the active
    /// tunnel uses; this RPC doesn't auto-detect because there
    /// might be several utuns up at once (Tailscale + WireGuard).
    pub tunnel_interface: String,
}

#[derive(Deserialize, Debug)]
pub struct DisableArgs {}

#[derive(Serialize, Debug)]
pub struct Result_ {
    pub success: bool,
    pub message: String,
}

/// Install the kill-switch anchor and load it into pf. Enables
/// pf if it isn't already running. Idempotent.
pub fn enable(args: EnableArgs) -> Result<Result_> {
    let iface = args.tunnel_interface;
    if !iface.starts_with("utun") {
        bail!("invalid tunnel_interface '{iface}' — must be utun*");
    }

    // Build the anchor's pf rules. Order matters in pf: explicit
    // pass before block, last-matching wins (without `quick`).
    // We use `quick` to short-circuit — first match wins, fewer
    // surprises.
    let rules = format!(
        "# SuperManager kill-switch anchor
# Generated by helper. Do not edit by hand — toggle via the GUI.

# Allow loopback (mDNS, local services, app introspection).
pass quick on lo0

# Allow tunnel egress + ingress.
pass quick on {iface} all

# Allow LAN traffic so printers / NAS / etc keep working.
pass quick to 10.0.0.0/8
pass quick to 172.16.0.0/12
pass quick to 192.168.0.0/16
pass quick to 169.254.0.0/16
pass quick to 224.0.0.0/4
pass quick to ff00::/8
pass quick to fe80::/10
pass quick to fd00::/8

# Allow DHCP, ARP, mDNS, IPv6 ND.
pass quick proto udp from any to any port 67:68
pass quick proto udp from any to any port 5353

# Allow Tailscale's underlay UDP (peer-to-peer over public IPs).
# Without this, kill-switch breaks tailnet itself when used with
# WireGuard kill-switch + Tailscale running side-by-side.
pass quick proto udp from any to any port 41641

# Block everything else.
block return out all
block return in all
"
    );

    fs::create_dir_all(Path::new(ANCHOR_FILE).parent().unwrap())
        .context("creating /etc/pf.anchors")?;
    fs::write(ANCHOR_FILE, rules).context("writing anchor file")?;

    // Make sure pf is enabled. `pfctl -E` is idempotent — returns
    // 0 with "pf enabled" or "pf already enabled".
    let _ = Command::new("/sbin/pfctl").arg("-E").output();

    // Load our anchor's rules. `-a <anchor>` loads into the
    // anchor namespace without touching the main ruleset.
    let load = Command::new("/sbin/pfctl")
        .args(["-a", ANCHOR_NAME, "-f", ANCHOR_FILE])
        .output()
        .context("running pfctl -f")?;
    if !load.status.success() {
        bail!(
            "pfctl load failed: {}",
            String::from_utf8_lossy(&load.stderr).trim()
        );
    }

    // Hook the anchor into the main ruleset. Without this, the
    // rules are loaded but never evaluated — pf only walks
    // anchors that are explicitly referenced. We add a tiny
    // referrer rule to the main ruleset that enters our anchor.
    //
    // Note: this isn't strictly idempotent; `pfctl -f -` on the
    // main ruleset replaces it. We only re-add the referrer if
    // it isn't there already.
    install_referrer_if_missing()?;

    Ok(Result_ {
        success: true,
        message: format!("Kill-switch active — only {iface} + LAN allowed"),
    })
}

/// Tear down the kill-switch anchor. After this, pf returns to
/// the state before `enable()` was called.
pub fn disable(_: DisableArgs) -> Result<Result_> {
    // Flush our anchor's rules.
    let _ = Command::new("/sbin/pfctl")
        .args(["-a", ANCHOR_NAME, "-F", "all"])
        .output();
    // Remove the anchor file so it doesn't get re-loaded on a
    // subsequent system reboot.
    let _ = fs::remove_file(ANCHOR_FILE);
    // Pull the referrer line out of the main ruleset.
    remove_referrer_if_present()?;
    Ok(Result_ {
        success: true,
        message: "Kill-switch removed".to_string(),
    })
}

/// Make sure the main pf ruleset includes our anchor reference.
/// Idempotent — only adds if not present.
fn install_referrer_if_missing() -> Result<()> {
    // Read current main ruleset and check for our anchor.
    let current = Command::new("/sbin/pfctl")
        .args(["-sr"])
        .output()
        .context("pfctl -sr")?;
    let stdout = String::from_utf8_lossy(&current.stdout);
    if stdout.contains(&format!("anchor \"{ANCHOR_NAME}\"")) {
        return Ok(());
    }
    // pf's main ruleset comes from /etc/pf.conf. We append a
    // single line referring to our anchor.
    let pf_conf = "/etc/pf.conf";
    let body = fs::read_to_string(pf_conf).context("reading /etc/pf.conf")?;
    let line = format!("\nanchor \"{ANCHOR_NAME}\"\nload anchor \"{ANCHOR_NAME}\" from \"{ANCHOR_FILE}\"\n");
    if !body.contains(&format!("anchor \"{ANCHOR_NAME}\"")) {
        let new_body = format!("{body}{line}");
        fs::write(pf_conf, new_body).context("writing /etc/pf.conf")?;
    }
    // Reload the full ruleset so the new anchor reference takes effect.
    let _ = Command::new("/sbin/pfctl")
        .args(["-f", pf_conf])
        .output();
    Ok(())
}

/// Strip our anchor reference from /etc/pf.conf if present.
fn remove_referrer_if_present() -> Result<()> {
    let pf_conf = "/etc/pf.conf";
    let body = fs::read_to_string(pf_conf).unwrap_or_default();
    let needle_anchor = format!("\nanchor \"{ANCHOR_NAME}\"\n");
    let needle_load = format!("load anchor \"{ANCHOR_NAME}\" from \"{ANCHOR_FILE}\"\n");
    let mut new_body = body.replace(&needle_anchor, "\n");
    new_body = new_body.replace(&needle_load, "");
    if new_body != body {
        fs::write(pf_conf, new_body).context("writing /etc/pf.conf")?;
        let _ = Command::new("/sbin/pfctl").args(["-f", pf_conf]).output();
    }
    Ok(())
}
